absolute_urls: false
timezone: 'Europe/Rome'
force_ssl: false

languages:
  supported: [en]
  include_default_lang: false

home:
  alias: '/home'
  hide_in_urls: true

pages:
  theme: quark
  markdown:
    extra: false
  process:
    markdown: true
    twig: false

cache:
  enabled: true
  check:
    method: file
  driver: auto
  prefix: 'g'

twig:
  cache: true
  debug: true
  auto_reload: true
  autoescape: false

assets:
  css_pipeline: false
  css_minify: true
  css_rewrite: true
  js_pipeline: false
  js_minify: true

errors:
  display: true
  log: true

debugger:
  enabled: false
  twig: true
  shutdown:
    close_connection: true

images:
  default_image_quality: 80
  cache_all: false

gpm:
  releases: stable
  verify_peer: true
  official_gpm_only: true
